### ISSUE TITLE
Composite key support

### ISSUE THREAD

**Issue by Ristovski** [litdb/litdb#6]
### Describe the issue

litdb does not seem to support composite keys of any kind (primary/unique), which makes porting some tables impossible, for example:
```sql
CREATE TABLE Foo (
    fooKey INT NOT NULL,
    barKey INT NOT NULL,
    misc TEXT NOT NULL,
    PRIMARY KEY (fooKey, barKey)
);
```

such composite keys can not be handled by the current code which simply generates `n` separate `PRIMARY KEY` statements (which throws `table "Foo" has more than one primary key`):
https://github.com/litdb/litdb/blob/888e18fa82d52d142230d83c674b8afc3d5cd35c/src/schema.ts#L116-L121

### Reproduction

```typescript
import { table, column } from 'litdb';
import { connect } from "@litdb/bun-sqlite";

const connection = connect({ fileName: ":memory:", strict: true })
const { sync: db } = connection

@table()
export class Foo {
    constructor(data?: Partial<Foo>) { Object.assign(this, data) }

    @column("INTEGER", { primaryKey: true, required: true })
    fooKey = 0

    @column("INTEGER", { primaryKey: true, required: true })
    barKey = 0

    @column("TEXT", { required: true })
    misc = 0
}

db.createTable(Foo)
```

> SQLiteError: table "Foo" has more than one primary key

### Expected behavior

litdb should support composite keys

### System Info

```shell
Linux
`litdb`: 0.0.26
`@litdb/bun-sqlite`: 0.0.9
`bun`: 1.1.39
```

### Validations

- [X] Confirm [Issue is reproducible](https://litdb.dev/bug-report) from the information provided

**Comment by mythz** [comment]
Composite Primary Keys should now be supported from this commit https://github.com/litdb/litdb/commit/e8df4db3ab72d1f1815ab2b69702b352a63661ed

thx for the repro!

**Comment by Ristovski** [comment]
@mythz What about composite unique keys - `UNIQUE (fooKey, barKey)` for example? This gets trickier since it would need to handle multiple _individual_ `unique: true` entries but also composite ones somehow.

**Comment by mythz** [comment]
Currently you'll need to use ALTER TABLE to add a unique constraint after calling `createTable`

Feel free to add a feature request for it to measure demand:
https://github.com/litdb/litdb/discussions/categories/ideas

Using ALTER TABLE should be a fairly straightforward workaround for adding custom constraints, will consider adding it to createTable if there's demand for it.
